version: '3'
services:
  client:
      build:
        context: .
        dockerfile: Dockerfile  
      container_name: client
      ports:
        - "3001:3001"
      volumes:
        - .:/app

      command: ["npm start"]